### PR TITLE
Use Sublime Text's dev channel by default

### PR DESCRIPTION
**Pull request by kyluca**
First attempt at #14 

Hey guys, I'm keen to get [Sublime Text's dev channel](https://www.sublimetext.com/3dev) available via this snap. At the moment we are tied to the stable releases (https://www.sublimetext.com/3) which come out once every few months, whereas their dev channel has much more frequent updates.

I'm not too familiar with Snaps/Snapcraft yet, but I'd hope there's a good way to make use of Snap Channels (stable, candidate, beta, edge) rather than publishing another Snap called sublime-text-dev. There may be a better way of handling this, but the way I see this working would be something like:

### Dev releases
1. Set the SUBLIME_CHANNEL to "dev" by default now
2. Trigger a build when a new tar package is published by ST in their dev channel (Are the builds currently triggered by new commits and manually? A daily timer would be nice here but I don't have access to the job config on https://build.snapcraft.io/user/snapcrafters/sublime-text)
2. When a build happens on https://build.snapcraft.io/user/snapcrafters/sublime-text/ the resulting snap should already go to the edge channel automatically I believe?
3. Users (with a ST license) install with `sudo snap install sublime-text --edge` (or get snap auto updates for free)

### Stable releases
1. Change the SUBLIME_CHANNEL to "stable" in snap/snapcraft.yaml
2. Trigger a build with a 'release commit' (e.g. git commit -m "v3.1 stable release"). Other options could include env vars depending on how the build is configured at https://build.snapcraft.io/user/snapcrafters/sublime-text.
3. Publish the snap from that build to the stable Snap channel (e.g. snapcraft release sublime-text 13 stable)
4. Revert the SUBLIME_CHANNEL to "dev" in snap/snapcraft.yaml so the daily dev builds can resume to go to the edge Snap channel.

Another option for the stable release workflow could be branching? Maintaining SUBLIME_CHANNEL="dev" on the master branch and only changing it to "stable" on a branch/tag (never merged)

Let me know what you guys think!

Cheers,
Kyle

### CODE REVIEW

**Comment by popey** [comment]
Sincere apologies for not getting to this in a timely fashion. I'm in two minds about this. Should we be building the upstream dev channel and putting that in a `track` in this snap, so users can choose which way to go from one snap. Or, should it be an entirely separate package. Do users typically (in the non-snap world) install both the stable and dev versions of sublime-text, so they can flip between them depending on broken-ness of dev?

We have both kinds of snaps in the store. Skype for example has a separate channel for their `insider` builds. Whereas vscode developers use two entirely separate applications. Which is best for Sublime Text?

@flexiondotorg what do you think?

**Comment by kyluca** [comment]
Hey no worries :smile: There's a tiny bit of a discussion on those two options in the Issue #14, so I'll try keep this short (or can copy/move across to consolidate later). Thanks for the example of Skype, I also saw [the "Parallel snap installs" topic](https://forum.snapcraft.io/t/parallel-snap-installs/5763) in [the Snapd roadmap here](https://forum.snapcraft.io/t/the-snapd-roadmap/1973). So for the use case you mentioned, in the future we would be able to install stable+dev channels side-by-side without needing separate snap packages (if they wanted to). I'd love to go with the "one snap,  multiple channels" approach rather than the "multiple snaps, one (upstream) channel (each)" approach.

Since snaps always have their four default channels (stable, candidate, beta, edge) it could seem redundant to have a 'stable' snap and a 'dev' snap with a total of eight channels (mapped to only two upstream channels):

1. `sublime-text`

    1. `stable`: (upstream) stable
    1. `candidate`: (upstream) stable
    1. `beta`: (upstream) stable
    1. `edge`: (upstream) stable

1. `sublime-text-dev`

    1. `stable`: (upstream) dev
    1. `candidate`: (upstream) dev
    1. `beta`: (upstream) dev
    1. `edge`: (upstream) dev

I think it could be a lot simpler with the one snap:

1. `sublime-text`
    1. `stable`: (upstream) stable
    1. `candidate`: (upstream) dev
    1. `beta`: (upstream) dev
    1. `edge`: (upstream) dev

**Comment by jwillikers** [comment]
How are you going to handle Sublime Text 4 which is currently under development? Packages are released regularly and mentioned on https://forum.sublimetext.com/t/sublime-text-discord-server/26063[their Discord server] in the *announcements* channel. They've also been publishing Sublime Text 4 packages for 64-bit ARM on Linux, which would be great to have access to as snaps.

**Comment by merlijn-sebrechts** [comment]
Closing this due to lack of activity

**Pull request closed without merging**
